name: "Build iOS Action"
author: "SparkFabrik"
branding:
  icon: "smartphone"
  color: "white"
description: "Build iOS project (.xcodeproj, .xcworkspace), export .ipa, optional upload to BrowserStack App Live."
inputs:
  project-path:
    description: "Project path"
    required: true
  team-id:
    description: "Team id"
    required: true
  team-name:
    description: "Team name"
    required: true
  workspace-path:
    description: "Workspace path"
    required: false
    default: ""
  export-method:
    description: "Choose app-store, ad-hoc, package, enterprise, development, or developer-id"
    required: false
    default: "app-store"
  configuration:
    description: "For example, Debug, Release"
    required: false
    default: "Release"
  output-path:
    description: "Output path of ipa"
    required: false
    default: "output.ipa"
  scheme:
    description: "Scheme"
    required: false
    default: ""
  update-targets:
    description: "Targets to be updated with mobileprovision, code signing identity, etc"
    required: false
    default: ""
  fastlane-version:
    description: "Specify the Fastlane version you wish to use"
    default: "2.213.0"
    required: false
  fastlane-env:
    description: "Name of the env file name to pass to fastlane --env"
    required: false
    default: ""
  ios-app-id:
    description: "The iOS application identifier; useful to sync a specific provisioning profile"
    required: false
runs:
  using: "node16"
  main: "dist/index.js"
