default_platform(:ios)

platform :ios do
  before_all do
    keychain_password = '12345678'
    create_keychain(
      name: "ios-build.keychain",
      password: keychain_password,
      default_keychain: true,
      unlock: true,
      timeout: 3600
    )
  end

  desc "Build"
  lane :build do
    use_workspace = !ENV['WORKSPACE_PATH'].empty?
    build_app(
      workspace: use_workspace ? ENV['WORKSPACE_PATH'] : nil,
      project: !use_workspace ? ENV['PROJECT_PATH'] : nil,
      configuration: ENV['CONFIGURATION'],
      scheme: ENV['SCHEME'],
      output_directory: File.dirname(ENV['OUTPUT_PATH']),
      output_name: File.basename(ENV['OUTPUT_PATH']),
      clean: true,
      result_bundle: true,
      export_method: ENV['EXPORT_METHOD'],
      export_team_id: ENV['TEAM_ID'],
      skip_package_ipa: true,
      skip_archive: true,
      destination: "generic/platform=iOS Simulator",
      silent: true,
      skip_codesigning: true,
      export_options: nil
    )
  end

  after_all do
    delete_keychain(
      name: "ios-build.keychain"
    )
  end
end
