default_platform(:ios)

platform :ios do
  before_all do
    keychain_password = '12345678'
    create_keychain(
      name: "ios-build.keychain",
      password: keychain_password,
      default_keychain: true,
      unlock: true,
      timeout: 3600
    )
  end

  desc "Build"
  lane :build do
    use_workspace = !ENV['WORKSPACE_PATH'].empty?
    build_app(
      workspace: use_workspace ? ENV['WORKSPACE_PATH'] : nil,
      project: !use_workspace ? ENV['PROJECT_PATH'] : nil,
      configuration: ENV['CONFIGURATION'],
      scheme: ENV['SCHEME'],
      derived_data_path: ENV['OUTPUT_PATH'],
      skip_package_ipa: true,
      skip_archive: true,
      destination: "generic/platform=iOS",
      silent: true,
      skip_codesigning: true
    )
  end

  after_all do
    delete_keychain(
      name: "ios-build.keychain"
    )
  end
end
