default_platform(:ios)

platform :ios do
  before_all do
    keychain_password = '12345678'
    create_keychain(
      name: "ios-build.keychain",
      password: keychain_password,
      default_keychain: true,
      unlock: true,
      timeout: 3600
    )
  end

  desc "Build"
  lane :build do
    use_workspace = !ENV['WORKSPACE_PATH'].empty?
    enable_automatic_code_signing(path: ENV['PROJECT_PATH'])
    build_app(
      workspace: use_workspace ? ENV['WORKSPACE_PATH'] : nil,
      project: !use_workspace ? ENV['PROJECT_PATH'] : nil,
      configuration: ENV['CONFIGURATION'],
      scheme: ENV['SCHEME'],
      output_directory: File.dirname(ENV['OUTPUT_PATH']),
      output_name: File.basename(ENV['OUTPUT_PATH']),
      clean: true,
      export_method: ENV['EXPORT_METHOD'],
      export_team_id: ENV['TEAM_ID'],
      silent: true,
      export_options: ENV['IOS_APP_ID'] != nil ? {
        provisioningProfiles: {
          "#{ENV['IOS_APP_ID']}" => "match AppStore #{ENV['IOS_APP_ID']}",
        },
      } : nil
    )
  end

  after_all do
    delete_keychain(
      name: "ios-build.keychain"
    )
  end
end
